### ISSUE TITLE
Ironsworn Oracles: implement 'roll twice' oracle results

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#22]
i've already started on this, just noting it here for the sake of record keeping

**Comment by XenotropicDev** [comment]
I was actually already working on this yesterday, but just hadn't commited the code yet. You can use [2x] the oracle json files and it will roll that table twice. It should work in most places, but due to the data structure/code it wasnt always known what the parent table was. I think I fix most of the places where this was true, but if you run into any places where you get an error of unknown table [2x] let me know so I can try and replicate/fix it.

**Comment by rsek** [comment]
cool, i've added that to the ironsworn 'roll twice' results where possible. the 'roll twice, if it's the same make it worse' results i'm just leaving as text for the moment.

**Comment by rsek** [comment]
#27
