### ISSUE TITLE
Please add⏬ reaction button to more posts by default

### ISSUE THREAD

**Issue by keithdok** [XenotropicDev/TheOracle#59]
It would be really convenient if the arrow_double_down reaction would be added by default to more posts, especially progress trackers, assets, and character cards. Thanks!

**Comment by XenotropicDev** [comment]
Thanks for the issue entry.

⏬ has been added as a default reaction to character cards, assets, initiative trackers, and scene challenges, delve sites, and player ships (starforged). 

It was not added to NPCs, Settlements, Planets, or Star Ships, mostly because I want to avoid too much clutter where there's less value, but I could be convinced to add it to any/all of these too.

I'm closing the issue, but feel free to comment more if you want.

**Comment by keithdok** [comment]
Wow, thanks so much! Will it show up retroactively (i.e. on cards for games already generated) or just new ones going forward?

**Comment by XenotropicDev** [comment]
Only on new ones. The bot doesn't really have a way to add reactions to messages it already created.
