### ISSUE TITLE
Empath asset always has the second option checked.

### ISSUE THREAD

**Issue by simon-toogood** [XenotropicDev/TheOracle#60]
**Steps to Reproduce**

-  With the bot in server, run !Asset Empath
- Take a look at the result

**Expected behaviour**
The first option only is checked, with reacts for parts 2 and 3.

**Current behaviour**
Option 1 and 2 are checked, and there's only a react for 3. 

Tried deleting the response and re-running the command, got the same result.

![image](https://user-images.githubusercontent.com/40660385/124401232-166f0a80-dd20-11eb-9271-00bd920127e0.png)

**Comment by XenotropicDev** [comment]
Thank you for the detailed issue post. I'll take a look at it and have a fix for it as soon as possible.

**Comment by simon-toogood** [comment]
No worries, thanks for the lovely bot, it's a great resource.

**Comment by XenotropicDev** [comment]
This issue was actually way bigger than just the Empath asset. Anyone who created an asset that had already had one of its abilities triggered by any other user of the bot would've gotten this behavior.

Should be fixed in the bot now, please delete and recreate any assets that are effected by this bug.
