### ISSUE TITLE
Player cards: Remove previous stat selection when a new stat is selected

### ISSUE THREAD

**Issue by GatesDA** [XenotropicDev/TheOracle#64]
If I select multiple Player Card stats and use one of the arrow reactions it gives me an error message ("Too many stats are active, please disable all but one.")

It would be cleaner for it to remove the previous selection.  For example, selecting Health then Spirit would remove the user's Health reaction so only Spirit remains.

**Comment by XenotropicDev** [comment]
I was hesitant to add this before because discord doesn't actually give a great way for bots to read/remove reactions in bulk, and doing so was slow, buggy, and would eat up the bot's API calls pretty quick. However I found a solution where the bot just looks at the number of reactions on the message and tries to remove the reaction if there's more than one reaction on it (other than the one just selected). This method is faster, and doesn't use nearly as many API calls, but it can still be a little buggy, and I'm assuming if any other users react to your player card's reactions it will create a lot of the same slow/bugyness as before.

So I'm going to enable it in the bot, but I'm also going to keep an eye on it and see if it needs more work, or need to be removed.

Thanks for the issue entry, and I hope you keep enjoying the bot!
