### ISSUE TITLE
Reference command doesn't show all commands in json data file

### ISSUE THREAD

**Issue by brandonm4** [XenotropicDev/TheOracle#80]
in ReferenceAutoComplete.cs
line 33

I changed to: 
//var initialMoves = new List<string> { "Face Danger", "Secure an Advantage" };
var initialMoves = moves.GetMoves().Select(m => m.Name).ToList();

That will autopopulate them from the file.

**Comment by XenotropicDev** [comment]
Unfortunately due to the auto complete item count limit of 25 within discord the bot can't display all the commands.
The idea was to limit the results that are returned so that the most common ones showed up and were easy to find, so I'd like to keep the curated list pretty short if possible (somewhere around 5 items). With all that said if you have suggestions on what should be in the default list I'd happily add them.
